version: "3.9"
services:

  bbjja_dev_appserver:
    build: .
    ports:
      - "80:8080"
    depends_on:
      - bbjja_dev_database_server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bbjja_dev_database_server:5432/bbjjadb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - bbjja_development_network
    volumes:
      - bbjja_application_volume:/var/lib/bbjja

  bbjja_dev_database_server:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bbjjadb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bbjja_development_network
    volumes:
      - bbjja_database_volume:/var/lib/mysql

  bbjja_dev_database_admin:
    image: adminer:latest
    restart: always
    ports:
      - "9090:8080"
    networks:
      - bbjja_development_network

networks:
  bbjja_production_network:
  bbjja_development_network:


volumes:
  bbjja_database_volume: {}
  bbjja_application_volume: {}
